port: "8000"
postgres:
  db:
    host: "db"
    port: "5432"
    username: "postgres"
    dbname: "todo_db"
    sslmode: "disable"
redis:                         
  host: "rdb"
  port: "6379"
  db: 2